# action.yml
name: 'Nuvla Application Deployer'
description: 'Deploy an application from Nuvla.io into an existing infrastructure'
inputs:
  api-key:  # user api key for login
    description: 'Nuvla.io User API Key'
    required: true
  api-secret: # user api secret for login
    description: 'Nuvla.io User API Secret'
    required: true
  module-id: # module id of the application to be deployed
    description: 'Module ID of the Nuvla.io application to be deployed'
    required: true
  credential-id:  # credential id of the infrastructure to be used
    description: 'Credential ID for the Nuvla.io infrastructure where to deploy the app'
    required: true
  environment:  # list of env to setup for the app deployemnt
    description: 'Comma separated list of variables for the app deployemnt (i.e. "ENV1=value1,..."'
    required: false
    default: ""
outputs:
  DEPLOYMENT_ID: # id of app
    description: 'ID of deployment in Nuvla.io'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --api-key
    - ${{ inputs.api-key }}
    - --api-secret
    - ${{ inputs.api-secret }}
    - --module-id
    - ${{ inputs.module-id }}
    - --credential-id
    - ${{ inputs.credential-id }}
    - --environment
    - ${{ inputs.environment }}